-- Dữ liệu mẫu cho câu hỏi theo topic
-- Ngày: 2025-08-17

-- Câu hỏi cho bài 1: Cơ bản về máy tính (lesson_id = 1)
INSERT INTO topic_exercises (lesson_id, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation_correct, explanation_wrong) VALUES
(1, 1, 'CPU là viết tắt của từ gì?', 'Central Processing Unit', 'Computer Processing Unit', 'Central Program Unit', 'Computer Program Unit', 'A', 'Chính xác! CPU là viết tắt của Central Processing Unit - Bộ xử lý trung tâm, là bộ phận chính thực hiện các phép tính và xử lý dữ liệu trong máy tính.', 'Không chính xác. CPU là viết tắt của Central Processing Unit (Bộ xử lý trung tâm), không phải các từ khác.'),
(1, 2, 'RAM có chức năng gì trong máy tính?', 'Lưu trữ dữ liệu vĩnh viễn', 'Lưu trữ dữ liệu tạm thời', 'Xử lý đồ họa', 'Kết nối mạng', 'B', 'Đúng rồi! RAM (Random Access Memory) có chức năng lưu trữ dữ liệu tạm thời khi máy tính đang hoạt động, giúp CPU truy cập nhanh chóng.', 'Sai rồi. RAM không lưu trữ vĩnh viễn mà chỉ lưu trữ tạm thời khi máy tính đang chạy.'),
(1, 3, 'Đơn vị đo dung lượng bộ nhớ nhỏ nhất là gì?', 'Bit', 'Byte', 'Kilobyte', 'Megabyte', 'A', 'Chính xác! Bit là đơn vị nhỏ nhất để đo dung lượng bộ nhớ, có thể chứa giá trị 0 hoặc 1.', 'Không đúng. Bit là đơn vị nhỏ nhất, 1 Byte = 8 Bit.'),
(1, 4, 'Hệ điều hành nào sau đây là mã nguồn mở?', 'Windows', 'macOS', 'Linux', 'iOS', 'C', 'Đúng! Linux là hệ điều hành mã nguồn mở, cho phép người dùng xem và chỉnh sửa mã nguồn.', 'Sai. Windows, macOS và iOS đều là hệ điều hành độc quyền, chỉ có Linux là mã nguồn mở.'),
(1, 5, 'Phần mềm nào sau đây là trình duyệt web?', 'Microsoft Word', 'Adobe Photoshop', 'Google Chrome', 'VLC Media Player', 'C', 'Chính xác! Google Chrome là một trình duyệt web phổ biến để truy cập internet.', 'Không đúng. Google Chrome là trình duyệt web, các phần mềm khác có chức năng khác.'),
(1, 6, 'SSD khác gì so với HDD?', 'SSD nhanh hơn và không có bộ phận chuyển động', 'SSD chậm hơn nhưng bền hơn', 'SSD và HDD giống nhau hoàn toàn', 'SSD chỉ dùng cho laptop', 'A', 'Đúng! SSD (Solid State Drive) nhanh hơn HDD và không có bộ phận cơ học chuyển động, do đó ít hỏng hóc hơn.', 'Sai. SSD nhanh hơn HDD và không có đĩa quay như HDD.'),
(1, 7, 'Virus máy tính là gì?', 'Phần mềm bảo vệ máy tính', 'Chương trình độc hại', 'Hệ điều hành', 'Trình duyệt web', 'B', 'Chính xác! Virus máy tính là chương trình độc hại có thể làm hại dữ liệu và hệ thống.', 'Không đúng. Virus là chương trình độc hại, không phải phần mềm bảo vệ.'),
(1, 8, 'Firewall có tác dụng gì?', 'Tăng tốc độ internet', 'Bảo vệ khỏi truy cập trái phép', 'Chỉnh sửa ảnh', 'Phát nhạc', 'B', 'Đúng! Firewall là hệ thống bảo mật giúp bảo vệ máy tính khỏi các truy cập trái phép từ mạng.', 'Sai. Firewall là công cụ bảo mật, không phải để tăng tốc internet.'),
(1, 9, 'Phím tắt Ctrl+C có chức năng gì?', 'Dán', 'Sao chép', 'Cắt', 'Hoàn tác', 'B', 'Chính xác! Ctrl+C là phím tắt để sao chép (copy) văn bản hoặc đối tượng đã chọn.', 'Không đúng. Ctrl+C là sao chép, Ctrl+V là dán, Ctrl+X là cắt.'),
(1, 10, 'URL là viết tắt của gì?', 'Universal Resource Locator', 'Uniform Resource Locator', 'Universal Reference Link', 'Uniform Reference Locator', 'B', 'Đúng! URL là Uniform Resource Locator - địa chỉ định vị tài nguyên thống nhất trên internet.', 'Sai. URL là Uniform Resource Locator, không phải các từ khác.'),
(1, 11, 'Phần mềm nào dùng để nén file?', 'Notepad', 'WinRAR', 'Calculator', 'Paint', 'B', 'Chính xác! WinRAR là phần mềm chuyên dụng để nén và giải nén file.', 'Không đúng. WinRAR là phần mềm nén file, các phần mềm khác có chức năng khác.'),
(1, 12, 'Bluetooth có tác dụng gì?', 'Kết nối internet', 'Kết nối không dây tầm ngắn', 'Chỉnh sửa video', 'Quét virus', 'B', 'Đúng! Bluetooth là công nghệ kết nối không dây tầm ngắn giữa các thiết bị.', 'Sai. Bluetooth dùng để kết nối không dây tầm ngắn, không phải internet.'),
(1, 13, 'Phần mềm nào sau đây là hệ quản trị cơ sở dữ liệu?', 'Microsoft Word', 'MySQL', 'Adobe Reader', 'Skype', 'B', 'Chính xác! MySQL là hệ quản trị cơ sở dữ liệu phổ biến.', 'Không đúng. MySQL là hệ quản trị cơ sở dữ liệu, các phần mềm khác có chức năng khác.'),
(1, 14, 'Cache trong máy tính có tác dụng gì?', 'Lưu trữ dữ liệu tạm thời để truy cập nhanh', 'Xóa virus', 'Kết nối mạng', 'Chỉnh sửa ảnh', 'A', 'Đúng! Cache lưu trữ dữ liệu tạm thời để CPU hoặc ứng dụng có thể truy cập nhanh hơn.', 'Sai. Cache dùng để lưu trữ tạm thời nhằm tăng tốc độ truy cập.'),
(1, 15, 'Phím F5 thường có chức năng gì?', 'Lưu file', 'Làm mới/Refresh', 'In ấn', 'Thoát chương trình', 'B', 'Chính xác! F5 thường được dùng để làm mới (refresh) trang web hoặc cửa sổ hiện tại.', 'Không đúng. F5 là phím làm mới, không phải lưu file hay in ấn.');

-- Câu hỏi cho bài 2: Mạng máy tính (lesson_id = 2)
INSERT INTO topic_exercises (lesson_id, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation_correct, explanation_wrong) VALUES
(2, 1, 'IP là viết tắt của từ gì?', 'Internet Protocol', 'Internal Program', 'Internet Program', 'Internal Protocol', 'A', 'Đúng! IP là viết tắt của Internet Protocol - giao thức internet, là giao thức chính để truyền dữ liệu trên mạng internet.', 'Sai. IP là viết tắt của Internet Protocol, không phải các từ khác.'),
(2, 2, 'Địa chỉ IP nào sau đây là hợp lệ?', '192.168.1.256', '192.168.1.1', '192.168.300.1', '192.168.1', 'B', 'Chính xác! 192.168.1.1 là địa chỉ IP hợp lệ. Mỗi octet trong địa chỉ IP phải từ 0-255.', 'Không đúng. Địa chỉ IP hợp lệ có 4 octet, mỗi octet từ 0-255.'),
(2, 3, 'HTTP là giao thức để làm gì?', 'Gửi email', 'Truyền tải trang web', 'Chia sẻ file', 'Kết nối từ xa', 'B', 'Đúng! HTTP (HyperText Transfer Protocol) là giao thức để truyền tải các trang web từ server đến trình duyệt.', 'Sai. HTTP dùng để truyền tải trang web, không phải gửi email hay chia sẻ file.'),
(2, 4, 'DNS có chức năng gì?', 'Bảo mật mạng', 'Chuyển đổi tên miền thành địa chỉ IP', 'Nén dữ liệu', 'Mã hóa dữ liệu', 'B', 'Chính xác! DNS (Domain Name System) chuyển đổi tên miền (như google.com) thành địa chỉ IP để máy tính có thể kết nối.', 'Không đúng. DNS dùng để chuyển đổi tên miền thành IP, không phải bảo mật hay mã hóa.'),
(2, 5, 'Port 80 thường được sử dụng cho giao thức nào?', 'HTTPS', 'HTTP', 'FTP', 'SMTP', 'B', 'Đúng! Port 80 là port mặc định cho giao thức HTTP (trang web không mã hóa).', 'Sai. Port 80 dành cho HTTP, HTTPS dùng port 443, FTP dùng port 21.'),
(2, 6, 'LAN là viết tắt của gì?', 'Large Area Network', 'Local Area Network', 'Long Area Network', 'Limited Area Network', 'B', 'Chính xác! LAN là Local Area Network - mạng cục bộ, kết nối các thiết bị trong phạm vi nhỏ như văn phòng, nhà.', 'Không đúng. LAN là Local Area Network (mạng cục bộ).'),
(2, 7, 'Router có chức năng chính là gì?', 'Lưu trữ dữ liệu', 'Định tuyến dữ liệu giữa các mạng', 'Mã hóa dữ liệu', 'Nén dữ liệu', 'B', 'Đúng! Router có chức năng định tuyến (routing) - chọn đường đi tốt nhất cho dữ liệu giữa các mạng khác nhau.', 'Sai. Router dùng để định tuyến dữ liệu, không phải lưu trữ hay mã hóa.'),
(2, 8, 'DHCP có tác dụng gì?', 'Tự động cấp phát địa chỉ IP', 'Bảo mật mạng', 'Nén dữ liệu', 'Chia sẻ file', 'A', 'Chính xác! DHCP (Dynamic Host Configuration Protocol) tự động cấp phát địa chỉ IP cho các thiết bị trong mạng.', 'Không đúng. DHCP dùng để cấp phát IP tự động, không phải bảo mật hay nén dữ liệu.'),
(2, 9, 'Subnet mask có tác dụng gì?', 'Mã hóa dữ liệu', 'Xác định phần mạng và phần host trong IP', 'Nén dữ liệu', 'Bảo mật mạng', 'B', 'Đúng! Subnet mask giúp xác định phần nào của địa chỉ IP là network và phần nào là host.', 'Sai. Subnet mask dùng để phân chia địa chỉ IP thành phần mạng và host.'),
(2, 10, 'Giao thức nào được sử dụng để gửi email?', 'HTTP', 'FTP', 'SMTP', 'DNS', 'C', 'Chính xác! SMTP (Simple Mail Transfer Protocol) là giao thức chính để gửi email.', 'Không đúng. SMTP dùng để gửi email, HTTP cho web, FTP cho file.'),
(2, 11, 'Firewall hoạt động ở lớp nào trong mô hình OSI?', 'Lớp 1 - Physical', 'Lớp 3 - Network', 'Lớp 7 - Application', 'Tất cả các lớp', 'D', 'Đúng! Firewall hiện đại có thể hoạt động ở nhiều lớp khác nhau trong mô hình OSI để bảo vệ toàn diện.', 'Sai. Firewall có thể hoạt động ở nhiều lớp, không chỉ một lớp cụ thể.'),
(2, 12, 'TCP và UDP khác nhau ở điểm nào chính?', 'TCP nhanh hơn UDP', 'TCP đáng tin cậy hơn UDP', 'UDP bảo mật hơn TCP', 'TCP và UDP giống nhau', 'B', 'Chính xác! TCP đảm bảo dữ liệu được truyền đầy đủ và đúng thứ tự, trong khi UDP nhanh nhưng không đảm bảo.', 'Sai. TCP đáng tin cậy hơn nhưng chậm hơn UDP.'),
(2, 13, 'HTTPS khác HTTP ở điểm gì?', 'HTTPS nhanh hơn', 'HTTPS có mã hóa SSL/TLS', 'HTTPS dùng port khác', 'Cả B và C đều đúng', 'D', 'Đúng! HTTPS có mã hóa SSL/TLS để bảo mật và sử dụng port 443 thay vì port 80 của HTTP.', 'Không hoàn toàn đúng. HTTPS khác HTTP ở cả mã hóa và port.'),
(2, 14, 'MAC Address có độ dài bao nhiêu bit?', '32 bit', '48 bit', '64 bit', '128 bit', 'B', 'Chính xác! MAC Address có độ dài 48 bit, thường được biểu diễn dưới dạng 6 cặp số hex.', 'Sai. MAC Address có 48 bit, không phải 32, 64 hay 128 bit.'),
(2, 15, 'VPN là viết tắt của gì?', 'Virtual Private Network', 'Very Private Network', 'Virtual Public Network', 'Very Public Network', 'A', 'Đúng! VPN là Virtual Private Network - mạng riêng ảo, tạo kết nối bảo mật qua internet.', 'Sai. VPN là Virtual Private Network (mạng riêng ảo).');