-- =====================================================
-- ADVANCED ENGLISH VOCABULARY DICTIONARY
-- =====================================================
-- This script adds more advanced vocabulary including adjectives, food, nature, etc.
USE eduapp;
-- COMMON ADJECTIVES
INSERT IGNORE INTO dictionary (word, vietnamese, english_definition, part_of_speech, difficulty) VALUES
('good', 'tốt', 'of high quality', 'adjective', 'beginner'),
('bad', 'xấu', 'of poor quality', 'adjective', 'beginner'),
('big', 'lớn', 'of considerable size', 'adjective', 'beginner'),
('small', 'nhỏ', 'of limited size', 'adjective', 'beginner'),
('large', 'lớn', 'of great size', 'adjective', 'beginner'),
('little', 'nhỏ', 'small in size', 'adjective', 'beginner'),
('long', 'dài', 'of great length', 'adjective', 'beginner'),
('short', 'ngắn', 'of small length', 'adjective', 'beginner'),
('tall', 'cao', 'of great height', 'adjective', 'beginner'),
('high', 'cao', 'extending upward', 'adjective', 'beginner'),
('low', 'thấp', 'not high', 'adjective', 'beginner'),
('wide', 'rộng', 'of great width', 'adjective', 'beginner'),
('narrow', 'hẹp', 'of small width', 'adjective', 'beginner'),
('thick', 'dày', 'having great depth', 'adjective', 'beginner'),
('thin', 'mỏng', 'having little depth', 'adjective', 'beginner'),
('heavy', 'nặng', 'of great weight', 'adjective', 'beginner'),
('light', 'nhẹ', 'of little weight', 'adjective', 'beginner'),
('strong', 'mạnh', 'having power', 'adjective', 'beginner'),
('weak', 'yếu', 'lacking strength', 'adjective', 'beginner'),
('fast', 'nhanh', 'moving quickly', 'adjective', 'beginner'),
('slow', 'chậm', 'moving at low speed', 'adjective', 'beginner'),
('quick', 'nhanh', 'done rapidly', 'adjective', 'beginner'),
('new', 'mới', 'recently made or created', 'adjective', 'beginner'),
('old', 'cũ', 'having existed for long time', 'adjective', 'beginner'),
('young', 'trẻ', 'having lived for short time', 'adjective', 'beginner'),
('hot', 'nóng', 'having high temperature', 'adjective', 'beginner'),
('cold', 'lạnh', 'having low temperature', 'adjective', 'beginner'),
('warm', 'ấm', 'moderately hot', 'adjective', 'beginner'),
('cool', 'mát', 'moderately cold', 'adjective', 'beginner'),
('wet', 'ướt', 'covered with water', 'adjective', 'beginner'),
('dry', 'khô', 'free from moisture', 'adjective', 'beginner'),
('clean', 'sạch', 'free from dirt', 'adjective', 'beginner'),
('dirty', 'bẩn', 'covered with dirt', 'adjective', 'beginner'),
('beautiful', 'đẹp', 'pleasing to look at', 'adjective', 'beginner'),
('ugly', 'xấu', 'unpleasant to look at', 'adjective', 'beginner'),
('pretty', 'xinh', 'attractive', 'adjective', 'beginner'),
('nice', 'đẹp', 'pleasant or attractive', 'adjective', 'beginner'),
('happy', 'vui', 'feeling pleasure', 'adjective', 'beginner'),
('sad', 'buồn', 'feeling sorrow', 'adjective', 'beginner'),
('angry', 'tức giận', 'feeling rage', 'adjective', 'beginner'),
('excited', 'hào hứng', 'feeling enthusiasm', 'adjective', 'beginner'),
('tired', 'mệt', 'needing rest', 'adjective', 'beginner'),
('hungry', 'đói', 'needing food', 'adjective', 'beginner'),
('thirsty', 'khát', 'needing drink', 'adjective', 'beginner'),
('sick', 'ốm', 'not healthy', 'adjective', 'beginner'),
('healthy', 'khỏe', 'in good health', 'adjective', 'beginner'),
('easy', 'dễ', 'not difficult', 'adjective', 'beginner'),
('hard', 'khó', 'difficult to do', 'adjective', 'beginner'),
('difficult', 'khó khăn', 'not easy', 'adjective', 'beginner'),
('simple', 'đơn giản', 'easy to understand', 'adjective', 'beginner'),
('important', 'quan trọng', 'of great significance', 'adjective', 'beginner'),
('interesting', 'thú vị', 'arousing curiosity', 'adjective', 'beginner'),
('boring', 'chán', 'not interesting', 'adjective', 'beginner'),
('funny', 'vui nhộn', 'causing laughter', 'adjective', 'beginner'),
('serious', 'nghiêm túc', 'not joking', 'adjective', 'beginner'),
('quiet', 'yên tĩnh', 'making little noise', 'adjective', 'beginner'),
('loud', 'to', 'making much noise', 'adjective', 'beginner'),
('busy', 'bận rộn', 'having much to do', 'adjective', 'beginner'),
('free', 'rảnh', 'not busy', 'adjective', 'beginner'),
('full', 'đầy', 'containing as much as possible', 'adjective', 'beginner'),
('empty', 'trống', 'containing nothing', 'adjective', 'beginner'),
('rich', 'giàu', 'having much money', 'adjective', 'beginner'),
('poor', 'nghèo', 'having little money', 'adjective', 'beginner'),
('expensive', 'đắt', 'costing much money', 'adjective', 'beginner'),
('cheap', 'rẻ', 'costing little money', 'adjective', 'beginner'),
('right', 'đúng', 'correct', 'adjective', 'beginner'),
('wrong', 'sai', 'incorrect', 'adjective', 'beginner'),
('true', 'thật', 'in accordance with fact', 'adjective', 'beginner'),
('false', 'giả', 'not true', 'adjective', 'beginner'),
('safe', 'an toàn', 'not dangerous', 'adjective', 'beginner'),
('dangerous', 'nguy hiểm', 'likely to cause harm', 'adjective', 'beginner'),

-- FOOD & DRINKS
('food', 'thức ăn', 'nutritious substance consumed', 'noun', 'beginner'),
('meal', 'bữa ăn', 'eating occasion', 'noun', 'beginner'),
('breakfast', 'bữa sáng', 'morning meal', 'noun', 'beginner'),
('lunch', 'bữa trưa', 'midday meal', 'noun', 'beginner'),
('dinner', 'bữa tối', 'evening meal', 'noun', 'beginner'),
('rice', 'cơm', 'staple food grain', 'noun', 'beginner'),
('bread', 'bánh mì', 'baked food made from flour', 'noun', 'beginner'),
('meat', 'thịt', 'animal flesh as food', 'noun', 'beginner'),
('fish', 'cá', 'aquatic animal as food', 'noun', 'beginner'),
('chicken', 'gà', 'poultry as food', 'noun', 'beginner'),
('egg', 'trứng', 'oval reproductive body', 'noun', 'beginner'),
('vegetable', 'rau', 'plant grown for food', 'noun', 'beginner'),
('fruit', 'trái cây', 'sweet plant product', 'noun', 'beginner'),
('apple', 'táo', 'round red or green fruit', 'noun', 'beginner'),
('banana', 'chuối', 'yellow curved fruit', 'noun', 'beginner'),
('orange', 'cam', 'citrus fruit', 'noun', 'beginner'),
('grape', 'nho', 'small round fruit', 'noun', 'beginner'),
('tomato', 'cà chua', 'red round fruit/vegetable', 'noun', 'beginner'),
('potato', 'khoai tây', 'starchy tuber', 'noun', 'beginner'),
('onion', 'hành', 'bulbous vegetable', 'noun', 'beginner'),
('carrot', 'cà rốt', 'orange root vegetable', 'noun', 'beginner'),
('water', 'nước', 'colorless liquid essential for life', 'noun', 'beginner'),
('milk', 'sữa', 'white liquid from mammals', 'noun', 'beginner'),
('coffee', 'cà phê', 'drink made from coffee beans', 'noun', 'beginner'),
('tea', 'trà', 'drink made from tea leaves', 'noun', 'beginner'),
('juice', 'nước ép', 'liquid from fruits', 'noun', 'beginner'),
('beer', 'bia', 'alcoholic drink', 'noun', 'beginner'),
('wine', 'rượu vang', 'alcoholic drink from grapes', 'noun', 'beginner'),
('sugar', 'đường', 'sweet substance', 'noun', 'beginner'),
('salt', 'muối', 'white seasoning', 'noun', 'beginner'),
('oil', 'dầu', 'liquid fat for cooking', 'noun', 'beginner'),
('butter', 'bơ', 'dairy product for cooking', 'noun', 'beginner'),
('cheese', 'phô mai', 'dairy product', 'noun', 'beginner'),
('cake', 'bánh ngọt', 'sweet baked dessert', 'noun', 'beginner'),
('cookie', 'bánh quy', 'small sweet baked item', 'noun', 'beginner'),
('chocolate', 'sô cô la', 'sweet brown confection', 'noun', 'beginner'),
('ice cream', 'kem', 'frozen sweet dessert', 'noun', 'beginner'),

-- NATURE & WEATHER
('nature', 'thiên nhiên', 'the natural world', 'noun', 'beginner'),
('weather', 'thời tiết', 'atmospheric conditions', 'noun', 'beginner'),
('sun', 'mặt trời', 'star that earth orbits', 'noun', 'beginner'),
('moon', 'mặt trăng', 'natural satellite of earth', 'noun', 'beginner'),
('star', 'ngôi sao', 'luminous celestial body', 'noun', 'beginner'),
('sky', 'bầu trời', 'space above earth', 'noun', 'beginner'),
('cloud', 'đám mây', 'visible mass of water vapor', 'noun', 'beginner'),
('rain', 'mưa', 'water falling from clouds', 'noun', 'beginner'),
('snow', 'tuyết', 'frozen precipitation', 'noun', 'beginner'),
('wind', 'gió', 'moving air', 'noun', 'beginner'),
('storm', 'bão', 'violent weather', 'noun', 'beginner'),
('tree', 'cây', 'woody perennial plant', 'noun', 'beginner'),
('flower', 'hoa', 'reproductive structure of plant', 'noun', 'beginner'),
('grass', 'cỏ', 'small green plants', 'noun', 'beginner'),
('leaf', 'lá', 'flat green part of plant', 'noun', 'beginner'),
('forest', 'rừng', 'large area of trees', 'noun', 'beginner'),
('mountain', 'núi', 'large natural elevation', 'noun', 'beginner'),
('hill', 'đồi', 'small mountain', 'noun', 'beginner'),
('river', 'sông', 'flowing body of water', 'noun', 'beginner'),
('lake', 'hồ', 'large body of water', 'noun', 'beginner'),
('sea', 'biển', 'large body of salt water', 'noun', 'beginner'),
('ocean', 'đại dương', 'very large sea', 'noun', 'beginner'),
('beach', 'bãi biển', 'sandy shore', 'noun', 'beginner'),
('island', 'đảo', 'land surrounded by water', 'noun', 'beginner'),
('rock', 'đá', 'hard mineral matter', 'noun', 'beginner'),
('stone', 'đá', 'small piece of rock', 'noun', 'beginner'),
('sand', 'cát', 'fine particles of rock', 'noun', 'beginner'),
('earth', 'trái đất', 'the planet we live on', 'noun', 'beginner'),
('ground', 'mặt đất', 'surface of earth', 'noun', 'beginner'),
('fire', 'lửa', 'burning gas or vapor', 'noun', 'beginner'),
('ice', 'đá', 'frozen water', 'noun', 'beginner'),

-- ANIMALS
('animal', 'động vật', 'living creature', 'noun', 'beginner'),
('cat', 'mèo', 'small domesticated carnivorous mammal', 'noun', 'beginner'),
('dog', 'chó', 'domesticated carnivorous mammal', 'noun', 'beginner'),
('bird', 'chim', 'feathered flying animal', 'noun', 'beginner'),
('fish', 'cá', 'aquatic animal', 'noun', 'beginner'),
('horse', 'ngựa', 'large four-legged animal', 'noun', 'beginner'),
('cow', 'bò', 'large farm animal', 'noun', 'beginner'),
('pig', 'heo', 'farm animal', 'noun', 'beginner'),
('sheep', 'cừu', 'woolly farm animal', 'noun', 'beginner'),
('chicken', 'gà', 'domestic fowl', 'noun', 'beginner'),
('duck', 'vịt', 'water bird', 'noun', 'beginner'),
('elephant', 'voi', 'large mammal with trunk', 'noun', 'beginner'),
('lion', 'sư tử', 'large wild cat', 'noun', 'beginner'),
('tiger', 'hổ', 'large striped cat', 'noun', 'beginner'),
('bear', 'gấu', 'large furry mammal', 'noun', 'beginner'),
('monkey', 'khỉ', 'primate', 'noun', 'beginner'),
('rabbit', 'thỏ', 'small furry animal', 'noun', 'beginner'),
('mouse', 'chuột', 'small rodent', 'noun', 'beginner'),
('snake', 'rắn', 'long reptile', 'noun', 'beginner'),
('frog', 'ếch', 'amphibian', 'noun', 'beginner'),

-- COLORS
('color', 'màu sắc', 'visual property of objects', 'noun', 'beginner'),
('red', 'đỏ', 'color of blood', 'adjective', 'beginner'),
('blue', 'xanh dương', 'color of sky', 'adjective', 'beginner'),
('green', 'xanh lá', 'color of grass', 'adjective', 'beginner'),
('yellow', 'vàng', 'color of sun', 'adjective', 'beginner'),
('orange', 'cam', 'color between red and yellow', 'adjective', 'beginner'),
('purple', 'tím', 'color between red and blue', 'adjective', 'beginner'),
('pink', 'hồng', 'light red color', 'adjective', 'beginner'),
('brown', 'nâu', 'color of wood', 'adjective', 'beginner'),
('black', 'đen', 'darkest color', 'adjective', 'beginner'),
('white', 'trắng', 'lightest color', 'adjective', 'beginner'),
('gray', 'xám', 'color between black and white', 'adjective', 'beginner'),

-- TIME & NUMBERS
('time', 'thời gian', 'indefinite continued progress of existence', 'noun', 'beginner'),
('day', 'ngày', 'period of 24 hours', 'noun', 'beginner'),
('night', 'đêm', 'time of darkness', 'noun', 'beginner'),
('morning', 'buổi sáng', 'early part of day', 'noun', 'beginner'),
('afternoon', 'buổi chiều', 'middle part of day', 'noun', 'beginner'),
('evening', 'buổi tối', 'end part of day', 'noun', 'beginner'),
('week', 'tuần', 'period of seven days', 'noun', 'beginner'),
('month', 'tháng', 'period of about 30 days', 'noun', 'beginner'),
('year', 'năm', 'period of 365 days', 'noun', 'beginner'),
('hour', 'giờ', 'period of 60 minutes', 'noun', 'beginner'),
('minute', 'phút', 'period of 60 seconds', 'noun', 'beginner'),
('second', 'giây', 'basic unit of time', 'noun', 'beginner'),
('today', 'hôm nay', 'this present day', 'adverb', 'beginner'),
('tomorrow', 'ngày mai', 'the day after today', 'adverb', 'beginner'),
('yesterday', 'hôm qua', 'the day before today', 'adverb', 'beginner'),
('now', 'bây giờ', 'at this moment', 'adverb', 'beginner'),
('later', 'sau này', 'at a future time', 'adverb', 'beginner'),
('early', 'sớm', 'before usual time', 'adverb', 'beginner'),
('late', 'muộn', 'after usual time', 'adverb', 'beginner'),
('always', 'luôn luôn', 'at all times', 'adverb', 'beginner'),
('never', 'không bao giờ', 'at no time', 'adverb', 'beginner'),
('sometimes', 'đôi khi', 'occasionally', 'adverb', 'beginner'),
('often', 'thường xuyên', 'frequently', 'adverb', 'beginner'),
('usually', 'thường', 'in most cases', 'adverb', 'beginner'),
('number', 'số', 'mathematical value', 'noun', 'beginner'),
('zero', 'số không', 'number 0', 'noun', 'beginner'),
('one', 'một', 'number 1', 'noun', 'beginner'),
('two', 'hai', 'number 2', 'noun', 'beginner'),
('three', 'ba', 'number 3', 'noun', 'beginner'),
('four', 'bốn', 'number 4', 'noun', 'beginner'),
('five', 'năm', 'number 5', 'noun', 'beginner'),
('six', 'sáu', 'number 6', 'noun', 'beginner'),
('seven', 'bảy', 'number 7', 'noun', 'beginner'),
('eight', 'tám', 'number 8', 'noun', 'beginner'),
('nine', 'chín', 'number 9', 'noun', 'beginner'),
('ten', 'mười', 'number 10', 'noun', 'beginner'),
('eleven', 'mười một', 'number 11', 'noun', 'beginner'),
('twelve', 'mười hai', 'number 12', 'noun', 'beginner'),
('twenty', 'hai mười', 'number 20', 'noun', 'beginner'),
('thirty', 'ba mười', 'number 30', 'noun', 'beginner'),
('forty', 'bốn mười', 'number 40', 'noun', 'beginner'),
('fifty', 'năm mười', 'number 50', 'noun', 'beginner'),
('hundred', 'trăm', 'number 100', 'noun', 'beginner'),
('thousand', 'nghìn', 'number 1000', 'noun', 'beginner'),
('first', 'thứ nhất', 'ordinal number 1st', 'adjective', 'beginner'),
('second', 'thứ hai', 'ordinal number 2nd', 'adjective', 'beginner'),
('third', 'thứ ba', 'ordinal number 3rd', 'adjective', 'beginner'),
('last', 'cuối cùng', 'final', 'adjective', 'beginner'),
('next', 'tiếp theo', 'following', 'adjective', 'beginner');

-- Success message
SELECT 'Advanced vocabulary added successfully!' as Status,
       COUNT(*) as 'Total Words in Dictionary' FROM dictionary;
